name: Run simple Hello World
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install flake8

      # Execute Test for altoro mutual fo headless chrome
      - name: Run test for hello world
        run: flake8 .
